[build.env]
passthrough = [
    "RUST_BACKTRACE",
    "RUST_LOG",
    "RUST_DEBUG",
    "DONT_RUSTFMT"
]

volumes = [
    "OUT_DIR",
]


[target.x86_64-unknown-linux-gnu]
image = "ankidroid/rslib-bridge:linux"

[target.x86_64-pc-windows-gnu]
image = "ankidroid/rslib-bridge:windows"