[build]
# override any global customizations, as the gradle plugin requires a specific path
target-dir = "target"

[env]
STRINGS_JSON = { value = "anki/out/strings.json", relative = true }
DESCRIPTORS_BIN = { value = "anki/out/descriptors.bin", relative = true }
PROTOC = { value = "anki/out/extracted/protoc/bin/protoc", relative = true }
GENERATED_PROTO_DIR = { value = "rsdroid/build/generated/source/backend", relative = true }
