// SPDX-License-Identifier: GPL-3.0-or-later

import org.gradle.api.DefaultTask
import org.gradle.api.GradleException
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.InputFile
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.TaskAction

/**
 * Replacement for AGP's `BuildConfig` without direct Android dependencies.
 *
 * [outputDir] is assigned by whoever registers the output as a generated source
 * directory (AGP's `addGeneratedSourceDirectory`, or `srcDir` on a JVM source set).
 */
abstract class GenerateBuildConfigTask : DefaultTask() {
    @get:Input
    abstract val ankiCommitHash: Property<String>

    @get:Input
    abstract val ankiDesktopVersion: Property<String>

    @get:Input
    abstract val backendGitCommitHash: Property<String>

    @get:InputFile
    abstract val cargoLock: RegularFileProperty

    @get:OutputDirectory
    abstract val outputDir: DirectoryProperty

    @TaskAction
    fun generate() {
        // the compiled fsrs version is resolved by the root Cargo.lock, not anki/Cargo.lock:
        // rslib-bridge consumes anki as a path dependency, whose lockfile cargo ignores
        //  name = "fsrs"
        //  version = "A.B.C"
        val lockText = cargoLock.get().asFile.readText()
        val fsrsVersion =
            Regex("""(?m)^name = "fsrs"\r?\nversion = "([^"]+)"""").find(lockText)?.groupValues?.get(1)
                ?: throw GradleException("Could not find the fsrs version in Cargo.lock")
        logger.lifecycle("BuildConfig: anki=${ankiCommitHash.get().take(8)} fsrs=$fsrsVersion")

        val outFile = outputDir.file("net/ankiweb/rsdroid/BuildConfig.kt").get().asFile
        outFile.parentFile.mkdirs()
        outFile.writeText(
            """
            |// Generated by the generateBuildConfig task. DO NOT EDIT.
            |package net.ankiweb.rsdroid
            |
            |object BuildConfig {
            |    const val ANKI_COMMIT_HASH: String = "${ankiCommitHash.get()}"
            |    const val ANKI_DESKTOP_VERSION: String = "${ankiDesktopVersion.get()}"
            |    const val FSRS_VERSION: String = "$fsrsVersion"
            |    const val BACKEND_GIT_COMMIT_HASH: String = "${backendGitCommitHash.get()}"
            |
            |    /** When the values above last changed (the task is skipped when up to date) */
            |    const val BACKEND_BUILD_TIME: Long = ${System.currentTimeMillis()}L
            |}
            |
            """.trimMargin(),
        )
    }
}
